# Generated by Django 5.0.14 on 2025-12-26 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookmark_bookmark_unique_user_post_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL에 사용될 식별자 (자동 생성)', max_length=100, unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, help_text='마지막 임시저장 시간', null=True, verbose_name='임시저장일'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='임시저장 상태', verbose_name='임시저장'),
        ),
        migrations.AddField(
            model_name='post',
            name='series_order',
            field=models.PositiveIntegerField(default=0, help_text='시리즈 내 게시글 순서', verbose_name='시리즈 순서'),
        ),
        migrations.CreateModel(
            name='PostSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='시리즈 제목')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL에 사용될 식별자', max_length=200, unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, help_text='시리즈에 대한 간단한 설명', verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '시리즈',
                'verbose_name_plural': '시리즈 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.postseries', verbose_name='시리즈'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='태그'),
        ),
    ]
